config/routes.rb
Fwendme::Application.routes.draw do

  root to: 'static_pages#root'

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:new, :create, :show, :index, :edit, :update] do
      resources :friendships, only: [:create, :new]
      resources :chats, only: [:new]
    end

    resource :session, only: [:new, :create, :destroy]

    resources :chats, except: [:new] do
      resources :messages, only: [:new, :create]
    end

    resources :chat_memberships, only: [:create, :new, :destroy]

    resources :messages, only: [:show, :create, :index]
  end



  resources :users, only: [:new, :create, :show, :index, :edit, :update] do
    resources :friendships, only: [:create, :new]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :chats, except: :index do
    resources :messages, only: :new
  end

  resources :chat_memberships, only: [:create, :new, :destroy]

  resources :messages, only: [:create, :show]

  post 'pusher/auth'

  get '/auth/google_oauth2/callback', to: 'oauth_callbacks#google'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :owned_chats,
  class_name: "Chat",
  foreign_key: :owner_id,
  primary_key: :id

  has_many :chat_memberships

  has_many :friendships

  has_many :friends,
  through: :friendships

  has_many :inverse_friendships,
  class_name: "Friendship",
  foreign_key: :friend_id

  has_many :inverse_friends,
  through: :inverse_friendships,
  source: :user

  has_many :messages

  has_many :bumps, inverse_of: :user

  has_many :chats, through: :chat_memberships, source: :chat

  attr_reader :password

  has_attached_file :avatar,
  :default_url => "Fwendatar.png",
  :styles => {
    :big => "40x40>",
    :small => "40x40#"
  }
  validates_attachment_content_type(
    :avatar,
    :content_type => /\Aimage\/.*\Z/
  )

  validates :email, presence: true
  validates :password_digest, presence: {message: "Password can't be blank"}
  validates :email, uniqueness: { message: "you're already signed up! Sign in instead."}
  validates :password, length: { minimum: 6, allow_nil: true}
  validates :email, length: { minimum: 5 }
  validates :session_token, presence: true


  after_initialize :ensure_session_token

  def self.find_by_google_auth_hash(auth_hash)
    User.find_by(uid: auth_hash[:uid], provider: auth_hash[:provider])
  end

  def self.create_by_google_auth_hash(auth_hash)
    User.create!(
      uid: auth_hash[:uid],
      provider: auth_hash[:provider],
      email: auth_hash[:info][:email],
      name: auth_hash[:info][:first_name],
      avatar:  auth_hash[:info][:image],
      password: SecureRandom.urlsafe_base64(8)
      )
  end


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return (user && user.valid_password?(password) ? user : nil)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def fwends
    self.friends + self.inverse_friends
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController

    before_action :require_signed_in!, except: [:new, :create]
    before_action :require_signed_out!, only: [:new, :create]

    wrap_parameters false

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.name ||= params["email"]
      if @user.save
        sign_in(@user)
        redirect_to edit_user_url(@user)
      else
        flash.now[:errors] = @user.errors.full_messages
        render json: @user
      end
    end

    def show
      puts params
      @user = User.find(params[:id])
      render :show
    end

    def edit
      @user = current_user
      render json: @user
    end

    def update
      @user = User.find(params[:id])

      if params[:fwendAdd]
        current_user.friendships.create!(friend_id: fwend_add_params[:friend_id])

      elsif params[:chatAdd]
        ChatMembership.create!(chat_id: chat_add_params[:chatId], user_id: chat_add_params[:memberId])

      else
        @user.update(user_params)

      render @user.errors.full_messages if flash.now[:errors]

      end

      render json: @user
    end

    def index
      @users = User.all - [current_user] - current_user.fwends
      render :index
    end

    private
    def user_params
      params.permit(:password, :email, :name, :avatar)
    end

    def chat_add_params
      params.require(:chatAdd).permit(:memberId, :chatId)
    end
    def fwend_add_params
      params.require(:fwendAdd).permit(:friend_id)
    end


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signed_in!, except: [:new, :create]
  before_action :require_signed_out!, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name ||= params["user"]["email"]
    if @user.save
      sign_in(@user)
      redirect_to :root
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:password, :email, :name, :avatar)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<figure class="user-avatar"><%= image_tag @user.avatar.url(:big), size: "45x45" %></figure>
<h3>Edit <%= @user.name %>'s account</h3>
<br><br>
<form action="<%= user_url(@user) %>" enctype="multipart/form-data" method="POST">
  <%= auth_token_input %>
  <input type="hidden" name= "_method" value= "PATCH" >
  <label>
    Email
    <input type="email" name="user[email]" value="<%= @user.email %>">
  </label>
<br>
  <label>
    Name
    <input type="text" name="user[name]" value="">
  </label>
<br>

<input id="user-avatar-upload" name="user[avatar]" type="file" value="<%= @user.avatar_file_name %>">


<br>
  <input type="submit" value="Submit">
</form>
  <%= link_to "Cancel", root_url%>

app/views/users/index.html.erb
<% @users.each do |user| %>
<% next if user == current_user %>
<% next if current_user.fwends.include?(user) %>
<%= user.name %>
<%= button_to "Add Fwend", user_friendships_url(user) %>
<% end %>

app/views/users/new.html.erb
<section class="splash-page">

</section>

  <section class="logo-back">
    <img class="logo-img"
         src="<%= asset_path('TagLine2.png') %>"
         alt="Fwendatar">

     <section class="session-type-choice group">
        <%= link_to "Sign in", new_session_url, id: "sign-in-button", class: "other-session-type switch-session-button session-type" %>
       <a id="sign-up-button" class="current-session-type session-type">Sign up</a>
     </section>
 </section>

     <section class="omni-auth group">
       <img src="<%= asset_path("google-plus.png") %>"
            class="omni-auth-logo"
            width="50"
            height="50"
            alt="Google Plus">
       <%= link_to "Sign in with Google",
                   "/auth/google_oauth2",
                   class: "omniauth-button",
                   id: "google-omni" %>
     </section>
  <section class="new-user-form">



    <form action="<%= users_url %>" class="session-form" method="post">
      <%= auth_token_input %>

      <section class="email-label credential">
        <label>
          <input class="sign-in-email credential-input"
                 type="email"
                 name="user[email]"
                 value=""
                 placeholder="Email">
        </label>
      </section>

      <section class="password-label credential">
        <label>
          <input class="sign-in-password credential-input"
                 type="password"
                 name="user[password]"
                 value=""
                 placeholder="Password">
        </label>
      </section>

      <input type="submit"
             class="start-session-button"
             value="Submit">

    </form>
  </section>
</section>


<form action="<%= session_url %>" class="demo-form" method="post">
  <%= auth_token_input %>

  <section class="email-label credential demo-input">
    <label>
      <input class="sign-in-email credential-demo"
             type="email"
             name="user[email]"
             value="frodo@shire.com"
             placeholder="Email">
    </label>
  </section>

  <section class="password-label credential demo-input">
    <label>
      <input class="sign-in-password credential-demo"
             type="password"
             name="user[password]"
             value="password"
             placeholder="Password">
    </label>
  </section>

  <input type="submit"
         class="start-demo-button"
         value="Demo User">

</form>

app/views/users/show.html.erb
<h1><%= @user.name %>'s page</h1>
<content>
  <p>Current Chat</p>
</content>