config/routes.rb
Fwendme::Application.routes.draw do

  root to: 'static_pages#root'

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:new, :create, :show, :index, :edit, :update] do
      resources :friendships, only: [:create, :new]
      resources :chats, only: [:new]
    end

    resource :session, only: [:new, :create, :destroy]

    resources :chats, except: [:new] do
      resources :messages, only: [:new, :create]
    end

    resources :chat_memberships, only: [:create, :new, :destroy]

    resources :messages, only: [:show, :create, :index]
  end



  resources :users, only: [:new, :create, :show, :index, :edit, :update] do
    resources :friendships, only: [:create, :new]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :chats, except: :index do
    resources :messages, only: :new
  end

  resources :chat_memberships, only: [:create, :new, :destroy]

  resources :messages, only: [:create, :show]

  post 'pusher/auth'

  get '/auth/google_oauth2/callback', to: 'oauth_callbacks#google'

end

app/models/chat.rb
class Chat < ActiveRecord::Base

  belongs_to :owner,
  class_name: "User",
  foreign_key: :owner_id,
  primary_key: :id

  attr_reader :portrait, :unread

  has_many :chat_memberships

  has_many :messages

  has_many :users, through: :chat_memberships, source: :user

  validates :title, :owner_id, presence: true

  has_attached_file :portrait,
  :default_url => "https://s3.amazonaws.com/Fwend.me/Fwendatar.png",
  :styles => {
    :big => "45x45",
    :small => "45x45"
  }

  has_attached_file :settings,
  :default_url => "chat_settings.png",
  :styles => {
    :big => "45x45",
    :small => "45x45"
  }

  has_attached_file :member_icon,
  :default_url => "Fwendatar_alt.png",
  :styles => {
    :big => "45x45",
    :small => "45x45"
  }


  validates_attachment_content_type(
    :portrait,
    :content_type => /\Aimage\/.*\Z/
  )

  def make_fwends
    self.users.each_with_index do |user, i|
      current_fwends = User.find(user.id).fwends.map{ |friend| friend.id }
      (i+1).upto(self.users.length-1) do |j|
        next if current_fwends.include?(self.users[j].id)
        Friendship.create(user_id: self.users[i].id, friend_id: self.users[j].id)
      end
    end
  end

  def is_member?(user)
    self.users.include?(user)
  end

  def unread(current_user_id)
    membership = ChatMembership.find_by_user_id_and_chat_id(current_user_id, self.id)
    membership ? membership.unread : 0
  end

  def clear_unreads(current_user_id)
    ChatMembership.find_by_user_id_and_chat_id(current_user_id, self.id)
                  .unread = 0
  end


end

app/controllers/api/chats_controller.rb
module Api
  class ChatsController < ApiController

    before_action :require_membership!, only: [:edit, :show]
    wrap_parameters false

    def new
      @chat = Chat.new
      render json: @chat
    end

    def create
      @chat = current_user.chats.new(chat_params)
      @chat.owner = current_user
      if @chat.save
        ChatMembership.create!(chat_id: @chat.id, user_id: @chat.owner.id)
        redirect_to chat_url(@chat)
      else
        flash[:errors] = @chat.errors.full_messages
        redirect_to :back
      end
    end

    def edit
      @chat = Chat.find(params[:id])
      @chat_membership = ChatMembership.where(chat_id: @chat.id, user_id: current_user.id).first
      render :show
    end

    def update
      @chat = Chat.find(params[:id])
      updated_params = chat_params

      if updated_params[:user_ids]
        updated_params[:user_ids] += @chat.users.map { |user| user.id.to_s }
      end

      if @chat.update(updated_params)
        @chat.make_fwends
        render json: @chat
      else
        render json: @chat.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      chat = Chat.find(params[:id])
      ChatMembership.where(chat_id: params[:id]).destroy_all
      chat.destroy
      render json: {}
    end

    def show
      @chat = Chat.includes(:users, :messages).find(params[:id])
      @messages = @chat.messages.reverse
      if @chat.is_member?(current_user)
        ChatMembership.find_by_chat_id_and_user_id(params[:id], current_user.id).update(unread: 0)
        render :show
      else
        render json: {errors: "Can't see this chat"}
      end
    end

    def index
      @chats = current_user.chats.reverse
      render :index
    end

    private
    def chat_params
      params.permit(:title, :description, :portrait, user_ids: [])
    end

  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :require_signed_in!
  before_action :require_membership!, only: [:edit, :show]

  def new
    @chat = Chat.new
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.owner = current_user
    if @chat.save
      ChatMembership.create!(chat_id: @chat.id, user_id: @chat.owner.id)
      redirect_to chat_url(@chat)
    else
      flash[:errors] = @chat.errors.full_messages
      redirect_to :back
    end
  end

  def edit
    @chat = Chat.find(params[:id])
    @chat_membership = ChatMembership.where(chat_id: @chat.id, user_id: current_user.id).first
  end

  def update
    @chat = Chat.find(params[:id])
    updated_params = chat_params

    if updated_params[:user_ids]
      updated_params[:user_ids] += @chat.users.map { |user| user.id.to_s }
    end

    if @chat.update(updated_params)
      @chat.make_fwends
      redirect_to chat_url(@chat)
    else
      flash.now[:errors] = @chat.errors.full_messages
      render :edit
    end
  end

  def destroy
    chat = Chat.find(params[:id])
    ChatMembership.where(chat_id: params[:id]).destroy_all
    chat.destroy
    redirect_to user_url(current_user)
  end

  def show
    @chat = Chat.includes(:users, :messages).find(params[:id])
    @messages = @chat.messages.reverse
  end

  def index
    @chats = Chat.all
  end

  private
  def chat_params
    params.require(:chat).permit(:title, :portrait, user_ids: [])
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/edit.html.erb
<form action="<%= chat_url(@chat) %>" enctype="multipart/form-data" method="POST">

<%= auth_token_input %>

<input type="hidden" name= "_method" value= "PATCH" >

<label>
  Chat Name
  <input type="text"
         value="<%= @chat.title %>"
         name = "chat[title]">
</label>

<br>

<label>
  Chat Description
  <input type="text"
         value="<%= @chat.description %>"
         name = "chat[description]">
</label>

<br>

<input id="chat_portrait" name="chat[portrait]" type="file">

<br><br>
<h3>Current Members</h3>
<% User.all.each do |user| %>
<% next if !@chat.users.include?(user) %>
<%= image_tag user.avatar.url, size: "45x45" %>
<% end %>



<ul>
<% user_count = 0 %>
<% User.all.each do |user| %>
<% next if @chat.users.include?(user) %>
<% next if !current_user.fwends.include?(user) %>
<% user_count += 1 %>
<li>
  <input type = "checkbox"
         name = "chat[user_ids][]" value="<%= user.id %>">
  <%= user.name %>
 </li>

<% end %>
</ul>
<% if user_count > 0 %>
<h3>Select which users to add</h3>
<% end %>
<input type="submit">

</form>
<%= link_to "Cancel", chat_url(params[:id]) %>
<%= button_to "Leave Chat", chat_membership_url(@chat_membership.id), method: :delete %>
<% if current_user.id == @chat.owner.id %>
<%= button_to "Delete This Chat", chat_url(params[:id]), method: :delete %>
<% end %>

app/views/chats/new.html.erb
<h3>New Chat</h3>
<form action="<%= chats_url %>" method="post">
  <%= auth_token_input %>
  <label>
    Title<br>
    <input type="text" name="chat[title]" value="">
  </label><br>
<br><br>
  <input type="submit" value="Create Chat">
</form>

app/views/chats/show.html.erb
<header class="chat-header">
<figure class="chat-logo" alt="chat logo">
<%= image_tag @chat.portrait.url(:big), size: "45x45" %>
</figure>

<section class="chat-descriptors">
  <h1><%= @chat.title %></h1>
  <h2><%= @chat.description %></h2>
</section>

<section class="chat-tools">
  <a class="chat-settings chat-options" href="<%= edit_chat_url(@chat) %>">
    O
  </a>
  <a class="close-chat chat-options" href="<%= root_url %>">
    X
  </a>
</section>

</header>

<article class="chat-window-body">

  <section class="chat-messages">
    <ul class="messages-list">

        <% @messages.each do |message| %>
        <li class="message">
          <%= image_tag message.user.avatar, size: "40x40" %>
          <%= "#{message.user.name}: #{message.content}" %><br>
        </li>
        <% end %>
    </ul>
  </section>

  <form action="<%= messages_url(@chat) %>" method="post">
    <%= auth_token_input %>
    <textarea type="text"
              value=""
              name="message[content]"
              class="new-message">
    </textarea>

    <input type="submit" class="send-message-button" value="Send Message">
  </form>

</article>